[domain_controllers]
dc01 ansible_host=192.168.10.10

[file_servers]
fs01 ansible_host=192.168.10.20

[windows:children]
domain_controllers
file_servers

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_user=CORP\\Administrator
ansible_password=SET_VIA_ANSIBLE_VAULT_OR_ENV
ansible_winrm_server_cert_validation=ignore
